name: carwash_booking
description: SplashSphere Connect — Customer App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.5.6
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true